# Generated by Django 2.2.5 on 2019-09-18 08:46

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Species',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('taxon_id', models.CharField(max_length=8, verbose_name='TAXON_ID')),
                ('scientific_display_nme', models.CharField(max_length=100, verbose_name='SCIENTIFIC_DISPLAY_NAME')),
                ('common_nme', models.CharField(max_length=100, verbose_name='COMMON_NAME')),
                ('taxon_type', models.CharField(max_length=30, verbose_name='TAXON_TYPE')),
                ('primary_cde', models.CharField(max_length=5, verbose_name='PRIMARY_CDE')),
            ],
        ),
        migrations.CreateModel(
            name='Observation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ufi', models.CharField(max_length=8, verbose_name='UFI')),
                ('date_added', models.DateField(auto_now_add=True, verbose_name='DATE_ADDED')),
                ('date_modified', models.DateField(auto_now=True, verbose_name='DATE_MODIFIED')),
                ('survey_start_date', models.DateField(verbose_name='SURVEY_START_DATE')),
                ('latitudedd_num', models.FloatField(verbose_name='LATITUDEDD_NUM')),
                ('longitudedd_num', models.FloatField(verbose_name='LONGITUDEDD_NUM')),
                ('data', django.contrib.postgres.fields.jsonb.JSONField()),
                ('scraped', django.contrib.postgres.fields.jsonb.JSONField()),
                ('species', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='observation.Species')),
            ],
        ),
    ]
