# Generated by Django 2.2.5 on 2019-10-05 08:55

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ObservationImport',
            fields=[
                ('id', models.UUIDField(default=uuid.UUID('e879a129-da78-4adc-97ca-f89c566ab1a1'), editable=False, primary_key=True, serialize=False)),
                ('csv', models.FileField(upload_to='imports/%Y/%m/%d/', verbose_name='CSV FILE')),
                ('date_added', models.DateField(auto_now_add=True, verbose_name='DATE ADDED')),
                ('date_modified', models.DateField(auto_now=True, verbose_name='DATE MODIFIED')),
                ('remarks', models.TextField(blank=True, null=True, verbose_name='REMARKS')),
            ],
        ),
        migrations.CreateModel(
            name='Species',
            fields=[
                ('id', models.UUIDField(default=uuid.UUID('52641030-5b12-48a1-b020-031acb4294ec'), editable=False, primary_key=True, serialize=False)),
                ('taxon_id', models.CharField(max_length=8, verbose_name='TAXON_ID')),
                ('scientific_display_nme', models.CharField(max_length=100, verbose_name='SCIENTIFIC_DISPLAY_NAME')),
                ('common_nme', models.CharField(max_length=100, verbose_name='COMMON_NAME')),
                ('taxon_type', models.CharField(max_length=30, verbose_name='TAXON_TYPE')),
                ('primary_cde', models.CharField(max_length=5, verbose_name='PRIMARY_CDE')),
            ],
        ),
        migrations.CreateModel(
            name='Observation',
            fields=[
                ('id', models.UUIDField(default=uuid.UUID('216e3b85-d47e-4384-b0db-9b7c801f57cd'), editable=False, primary_key=True, serialize=False)),
                ('ufi', models.CharField(max_length=8, verbose_name='UFI')),
                ('date_added', models.DateField(auto_now_add=True, verbose_name='DATE_ADDED')),
                ('date_modified', models.DateField(auto_now=True, verbose_name='DATE_MODIFIED')),
                ('latitudedd_num', models.FloatField(verbose_name='LATITUDEDD_NUM')),
                ('longitudedd_num', models.FloatField(verbose_name='LONGITUDEDD_NUM')),
                ('lat_long_accuracydd_int', models.IntegerField(verbose_name='LAT_LONG_ACCURACYDD_INT')),
                ('sampling_method_desc', models.CharField(max_length=100, verbose_name='SAMPLING_METHOD_DESC')),
                ('record_type', models.CharField(blank=True, max_length=100, null=True, verbose_name='RECORD_TYPE')),
                ('sv_record_count', models.IntegerField(blank=True, null=True, verbose_name='SV_RECORD_COUNT')),
                ('lga_ufi', models.IntegerField(blank=True, null=True, verbose_name='LGA_UFI')),
                ('cma_no', models.IntegerField(blank=True, null=True, verbose_name='CMA_NO')),
                ('park_id', models.IntegerField(blank=True, null=True, verbose_name='PARK_ID')),
                ('survey_id', models.IntegerField(blank=True, null=True, verbose_name='SURVEY_ID')),
                ('reliability', models.CharField(blank=True, max_length=20, null=True, verbose_name='RELIABILITY')),
                ('reliability_txt', models.CharField(blank=True, max_length=20, null=True, verbose_name='RELIABILITY_TXT')),
                ('rating_int', models.IntegerField(blank=True, null=True, verbose_name='RATING_INT')),
                ('observation_import', models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, to='observation.ObservationImport')),
                ('species', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='observation.Species')),
            ],
        ),
    ]
