# Generated by Django 2.2 on 2019-09-21 07:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('observation', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='observation',
            name='survey_start_date',
        ),
    ]
