# Generated by Django 2.2.5 on 2019-10-06 05:27

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('observation', '0002_auto_20191006_1623'),
    ]

    operations = [
        migrations.AlterField(
            model_name='observation',
            name='id',
            field=models.UUIDField(default=uuid.UUID('3d06b4bb-352a-4317-b951-0bdb7f310fe7'), editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='observationimport',
            name='id',
            field=models.UUIDField(default=uuid.UUID('98369b28-8660-4f74-a014-5056c631700b'), editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='species',
            name='id',
            field=models.UUIDField(default=uuid.UUID('57826d29-9025-419e-8d58-669f062ecb23'), editable=False, primary_key=True, serialize=False),
        ),
    ]
