# Generated by Django 2.2.5 on 2019-10-06 05:31

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('observation', '0003_auto_20191006_1627'),
    ]

    operations = [
        migrations.AlterField(
            model_name='observation',
            name='id',
            field=models.UUIDField(default=uuid.UUID('439b4060-4fc6-4e07-b57c-39208e2dc267'), editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='observationimport',
            name='id',
            field=models.UUIDField(default=uuid.UUID('36fe6c57-297b-44cb-83d6-781c9a9b8155'), editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='species',
            name='id',
            field=models.UUIDField(default=uuid.UUID('ba9ba2d4-8cd2-48e9-968b-3a998437327d'), editable=False, primary_key=True, serialize=False),
        ),
    ]
