# Generated by Django 2.2.5 on 2019-10-05 08:54

import django.contrib.postgres.fields
from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Estimator',
            fields=[
                ('id', models.UUIDField(default=uuid.UUID('24f5b3ab-dd62-42b2-8738-758befa2bdbd'), editable=False, primary_key=True, serialize=False)),
                ('scaler_set', models.CharField(choices=[('standard', 'standard'), ('minmax', 'minmax'), ('quantile', 'quantile'), ('none', 'none')], default='none', max_length=10, verbose_name='scaler')),
                ('dimensionality_reduction_set', models.CharField(choices=[('pca', 'pca'), ('randomized', 'random'), ('none', 'none')], default='none', max_length=10, verbose_name='reduce_dim')),
                ('split_type', models.CharField(choices=[('none', 'train'), ('tt', 'train-test'), ('tvt', 'train-test-validate')], default='none', max_length=10, verbose_name='tt_split')),
                ('test_size', models.FloatField(verbose_name='test')),
                ('validate_size', models.FloatField(verbose_name='validate')),
                ('dataset', django.contrib.postgres.fields.ArrayField(base_field=models.UUIDField(null=True), size=None)),
            ],
        ),
        migrations.CreateModel(
            name='TrainedEstimator',
            fields=[
                ('id', models.UUIDField(default=uuid.UUID('45865112-2439-4481-a382-844124f74976'), editable=False, primary_key=True, serialize=False)),
                ('pickled_estimator', models.BinaryField(verbose_name='pickled_estimator')),
            ],
        ),
    ]
