# Generated by Django 2.2.5 on 2019-10-06 05:23

import django.contrib.postgres.fields
from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('estimator', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='estimator',
            name='dataset',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.UUIDField(blank=True, null=True), size=None),
        ),
        migrations.AlterField(
            model_name='estimator',
            name='id',
            field=models.UUIDField(default=uuid.UUID('f15e531f-b2fe-4aa5-817c-3c92aefe8fb6'), editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='trainedestimator',
            name='id',
            field=models.UUIDField(default=uuid.UUID('f8d913e9-0fba-4725-9b41-82770e7bc940'), editable=False, primary_key=True, serialize=False),
        ),
    ]
