# Generated by Django 2.2.5 on 2019-10-06 05:27

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('estimator', '0002_auto_20191006_1623'),
    ]

    operations = [
        migrations.AlterField(
            model_name='estimator',
            name='dimensionality_reduction_set',
            field=models.CharField(blank=True, choices=[('pca', 'pca'), ('randomized', 'random'), ('none', 'none')], default='none', max_length=10, verbose_name='reduce_dim'),
        ),
        migrations.AlterField(
            model_name='estimator',
            name='id',
            field=models.UUIDField(default=uuid.UUID('438f63ca-48b5-44fe-8dc2-47804a0ff948'), editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='estimator',
            name='scaler_set',
            field=models.CharField(blank=True, choices=[('standard', 'standard'), ('minmax', 'minmax'), ('quantile', 'quantile'), ('none', 'none')], default='none', max_length=10, verbose_name='scaler'),
        ),
        migrations.AlterField(
            model_name='estimator',
            name='split_type',
            field=models.CharField(blank=True, choices=[('none', 'train'), ('tt', 'train-test'), ('tvt', 'train-test-validate')], default='none', max_length=10, verbose_name='tt_split'),
        ),
        migrations.AlterField(
            model_name='trainedestimator',
            name='id',
            field=models.UUIDField(default=uuid.UUID('ce5d89c9-7db1-47c0-a899-8120de0a9f23'), editable=False, primary_key=True, serialize=False),
        ),
    ]
