# Generated by Django 2.2.5 on 2019-10-06 05:31

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('estimator', '0003_auto_20191006_1627'),
    ]

    operations = [
        migrations.AlterField(
            model_name='estimator',
            name='dimensionality_reduction_set',
            field=models.CharField(choices=[('pca', 'pca'), ('randomized', 'random'), ('none', 'none')], default='none', max_length=10, verbose_name='reduce_dim'),
        ),
        migrations.AlterField(
            model_name='estimator',
            name='id',
            field=models.UUIDField(default=uuid.UUID('b598ccee-9e41-4681-a94d-a65575359eb5'), editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='estimator',
            name='scaler_set',
            field=models.CharField(choices=[('standard', 'standard'), ('minmax', 'minmax'), ('quantile', 'quantile'), ('none', 'none')], default='none', max_length=10, verbose_name='scaler'),
        ),
        migrations.AlterField(
            model_name='estimator',
            name='split_type',
            field=models.CharField(choices=[('none', 'train'), ('tt', 'train-test'), ('tvt', 'train-test-validate')], default='none', max_length=10, verbose_name='tt_split'),
        ),
        migrations.AlterField(
            model_name='estimator',
            name='test_size',
            field=models.FloatField(blank=True, null=True, verbose_name='test'),
        ),
        migrations.AlterField(
            model_name='estimator',
            name='validate_size',
            field=models.FloatField(blank=True, null=True, verbose_name='validate'),
        ),
        migrations.AlterField(
            model_name='trainedestimator',
            name='id',
            field=models.UUIDField(default=uuid.UUID('68c67624-5776-4271-bfdd-9249b2bdbb18'), editable=False, primary_key=True, serialize=False),
        ),
    ]
